import { Geist, Geist_Mono } from "next/font/google";
import React from "react";
import Navbar from "./components/navbar/page";
import Footer from "./components/footer/page";
import "./globals.css";
import Head from "next/head";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      

      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

       
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
